default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("ACTIVE_RECORD_CONNECTION_POOL") { 20 } %>
  connect_timeout: 5
  host: mercury-postgres
  # host: localhost
  user: mercury-partner
  variables:
    statement_timeout: 15s
    lock_timeout: 10s

development:
  <<: *default
  database: mercury-partner

production:
  <<: *default
  database: mercury-partner

test:
  <<: *default
  host: localhost
  user:
  database: mercury-partner-test
  pool: 1
